const lightImages = {
    WarningPopupLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556483/WarningPopupLight_zu22iv.webp",
    yourBorrowLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556483/your-borrowLight_g6gzo0.webp",
    yourSuppliesWithdrawPopupLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556483/your-supplies-withdraw-popupLight_gtzvff.webp",
    yourBorrowRepayPopupLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556483/your-borrow-repay-popupLight_cgugkk.webp",
    youSuppliesLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556483/you-suppliesLight_vheb9a.webp",
    marketPageDetailsLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556482/market-page-detailsLight_brrsdp.webp",
    MarketPageSmallLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556482/MarketPageSmallLight_mxkpws.webp",
    marketPageLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556482/market-pageLight_ed2puc.webp",
    userInformationLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556482/userInformationLight_exsejw.webp",
    riskDetailsLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556482/risk-detailsLight_fl8wov.webp",
    LiquidationSuccessfullLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556482/LiquidationSuccessfullLight_tmfbft.webp",
    liquidationTableLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556482/liquidation-tableLight_jrkh65.webp",
    marketNavDetailsLightSmall: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556482/marketNavDetailsLightSmall_nzzjob.webp",
    faucetPopupLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556481/faucet-popupLight_prmm7a.webp",
    DashboardPageSmallLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556481/DashboardPageSmallLight_onqonc.webp",
    faucetPageLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556481/faucet-pageLight_g5qxcv.webp",
    FaucetSmallLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556481/FaucetSmallLight_jjswgs.webp",
    DashboardPageLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556481/Dashboard-page-light_yficiv.webp",
    getDebtStatusButtonLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556481/get-debt-status-buttonLight_wacxwe.webp",
    dashboardNavDetailsMenuLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556481/dashboardNavDetailsMenuLight_byohby.webp",
    dfinanceHomepageLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556480/dfinance-homepageLight_ekzavv.webp",
    colateralInformationCallLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556480/colateralInformationCallLight_npaqdf.webp",
    assetsToSupplyPopupLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556480/assets-to-supply-popupLight_urx6mr.webp",
    CollateralInformationLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556480/CollateralInformationLight_anngxi.webp",
    faucetButtonLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556480/faucet-buttonLight_lkbriw.webp",
    dashboardNavDetailsLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556480/dashboard-nav-detailsLight_fzgw26.webp",
    assetsToSupplyLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556479/assetsToSupplyLight_ocf1yn.webp",
    assetsToBorrowPopupLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556479/assets-to-borrow-popupLight_zhlzmy.webp",
    DashboarNavDetailsLightSmall: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556479/DashboarNavDetailsLightSmall_gpioft.webp",
    DfinanceHomeLightSmall: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556479/DfinanceHomeLightSmall_lfpozi.webp",
    DebtInformationLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556479/DebtInformationLight_ommun1.webp",
    assetsToBorrowLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556478/assets-to-borrowLight_nv6qsv.webp",
    LiquidatebuttonLight:"https://res.cloudinary.com/dxcmkla3l/image/upload/v1735556482/Liquidate-buttonLight_izsknx.webp",
    supplySupplyLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735883165/supply_supply_light_xitd0t.webp",
    supplyApproveLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735883165/supply_approve_light_adoxz2.webp",
    repayRepayLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735883280/repay_repay_light_j39ibe.webp",
    repayApproveLight: "https://res.cloudinary.com/dxcmkla3l/image/upload/v1735883280/repay_approve_light_ayllt6.webp",
  };
  
  export default lightImages;